pyprland.plugins = [ "monitors" ]

[monitors.hotplug_commands]
"Microstep" = "wlrlui one-screen"

 # work
[monitors.placement.CJFH277Q3HCB]
left_end_of = "eDP-1"
transform = 1
scale = 0.83

# home

[monitors.placement.BenQ]
top_middle_of = "DP-1"

