pyprland.plugins = [ "shortcuts_menu" ]

[pyprland.variables]
headphones_addr = '43:42:54:56:59:34'
hdmi_capture = 'USB3.0'

[shortcuts_menu]
command_start = "󰜎"
engine = "rofi"
parameters = "-p 🍰 -dmenu -i -theme ~/.config/rofi/rounded-nord-dark.rasi"

[shortcuts_menu.entries]

"Jira ticket (open)" = 'jisho "$(wl-paste)"'
"WIKI" = "xdg-open http://localhost:8000/"
"Serial USB Term" = [
    {name="speed", options=["115200", "9600", "38400", "115200", "25600", "512000"] },
    {name="device", command="ls -1 /dev/ttyUSB*; ls -1 /dev/ttyACM*" },
    "[term] miniterm --raw --eol LF [device] [speed]"
]
"Fetch window" = "pypr fetch_client_menu"

"Jira CheatSheet" = "xdg-open https://cheatography.com/rhorber/cheat-sheets/jira-text-formatting-notation/"

"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.5; hyprpicker --format [format] | wl-copy"
]

"Copy password" = [
    {name="what", command="gopass ls --flat"},
    "gopass show -c [what]"
]
"Update/Change password" = [
    {name="what", command="gopass ls --flat"},
    "[term] -- gopass generate -s --strict -t '[what]' && gopass show -c '[what]'"
]

"Clipboard history" = [
    {name="entry", command="cliphist list", filter="s/\t.*//"},
    "cliphist decode '[entry]' | wl-copy"
]

"Kill" = [
    {name="what", options=["buckle", "ruff", "ruff_lsp"]},
    "pkill [what]"
]

"Layout" = [
    {name="profile", command="wlrlui -l | sed 's/^ - //'"},
    "wlrlui \"[profile]\""
]

Screenshot = "screenshoter.sh"

[shortcuts_menu.entries.WM]

Relayout = "pypr relayout"
Reload = "hyprctl reload; pypr reload; pypr relayout"
"Hyprland socket" = '[term] socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"'
"Hyprland logs" = '[term] tail -f $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log'


[shortcuts_menu.entries."Sound / Audio"]

"Network ready" = "pactl load-module module-zeroconf-discover"
"Disconnect Headphones" =  "bluetoothctl disconnect [headphones_addr]"

[shortcuts_menu.entries."HDMI Capture"]

"Stop background" = "pkill mpvpaper"
"Play background" = [
{name="screen", command="hyprctl monitors |grep ^Monitor| cut -d ' ' -f2"},
    '''
    mpvpaper -o "--demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg" [screen] av://v4l2:$(v4l2-ctl --list-devices |grep -A1 "[hdmi_capture]" | tail -n 1  | sed -E 's/^\s*//g')
    '''
]
"Play in a window" = '''
    mpv --cache=no --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:$(v4l2-ctl --list-devices |grep -A1 "[hdmi_capture]" | tail -n 1  | sed -E 's/^\s*//g')
    '''
